// This is automatically generated by the Tiger compiler.
// Do NOT modify!

#include<memory.h>
// structures
struct Sum
{
  struct Sum_vtable *vptr;
  int isObjOrArray;
  int length;
  void* forwarding;
};
char Sum_gc_map[]="";
struct Doit
{
  struct Doit_vtable *vptr;
  int isObjOrArray;
  int length;
  void* forwarding;
};
char Doit_gc_map[]="";
// vtables structures
struct Sum_vtable
{
  char *Sum_gc_map;
};

struct Doit_vtable
{
  char *Doit_gc_map;
  int (*doit)();
};


extern void *prev;
// methods declear
int Doit_doit(struct Doit * this, int n);
// vtables
struct Sum_vtable Sum_vtable_ = 
{
  Sum_gc_map,
};

struct Doit_vtable Doit_vtable_ = 
{
  Doit_gc_map,
  Doit_doit,
};


// methods
char *Doit_doit_arguments_gc_map = "10";
int Doit_doit_locals_gc_map = 0;
struct Doit_doit_gc_frame{
void *prev;
char *arguments_gc_map;
int *arguments_base_address;
int locals_gc_map;
};
int Doit_doit(struct Doit * this, int n)
{
  struct Doit_doit_gc_frame frame;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = Doit_doit_arguments_gc_map;
  frame.arguments_base_address = (int*)&this;
  frame.locals_gc_map = Doit_doit_locals_gc_map;
  int sum;
  int i;

  i = 0;
  sum = 0;
  while (i < n)
    {

      sum = sum + i;
      i = i + 1;
    }

prev = frame.prev;
  return sum;
}

// main method
struct Tiger_main_gc_frame{
void *prev;
char *arguments_gc_map;
int *arguments_base_address;
int locals_gc_map;
  struct Doit * x_0;
};
char *Tiger_main_arguments_gc_map = "";
int Tiger_main_locals_gc_map = 1;
int Tiger_main ()
{
  struct Tiger_main_gc_frame frame;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = Tiger_main_arguments_gc_map;
  frame.locals_gc_map = Tiger_main_locals_gc_map;
  {

    System_out_println ((frame.x_0=((struct Doit*)(Tiger_new (&Doit_vtable_, sizeof(struct Doit)))), frame.x_0->vptr->doit(frame.x_0, 101)));
  }
  prev = frame.prev;
}



